toolkit/mailer/urls.py
from django.urls import path
from .views import job_cancel, jobs_list, jobs_table

app_name = "mailer"

urlpatterns = [
    # Try to cancel a job
    path("job/<int:job_id>/delete/", job_cancel, name="job-delete"),
    # View all jobs
    path("jobs/", jobs_list, name="jobs-list"),
    # Retrieve job table fragment
    path("job-table/", jobs_table, name="jobs-table"),
]

urls.py
import cube.settings
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    url(r'^programme/', include('cube.diary.urls')),
    url(r'^whatson/', include('cube.diary.urls')),
    url(r'^diary/', include('cube.diary.urls')),
    url(r'^auth/', include('cube.auth.urls')),
    # Examples:
    # url(r'^$', 'cube.views.home', name='home'),
    # url(r'^cube/', include('cube.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
    url(r'^static/(.*)$', 'django.views.static.serve',{'document_root':cube.settings.STATIC_ROOT}),

)

toolkit/index/templates/base_admin.html
{% extends "base.html" %}

{% block css %}
<link href='http://fonts.googleapis.com/css?family=Roboto+Mono:400,100,100italic,300,300italic,500' rel='stylesheet' type='text/css'>
<!--[if lte IE 8]>
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto+Mono:400" />
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto+Mono:100" />
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto+Mono:100italic" />
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto+Mono:300" />
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto+Mono:300italic" />
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto+Mono:500" />
<![endif]-->
<link rel="stylesheet" href="{{ STATIC_URL }}css/lib/bootstrap.min.css">
<style>
body {
  padding: 5rem 1.4rem;
}
#base-admin-logout-form {
  display: inline;
}
#base-admin-logout-form button {
  background: none;
  border: none;
}
</style>
{% endblock %}

{% block script %}
    <script src="{{ STATIC_URL }}js/lib/jquery-3.5.1.min.js"></script>
    <script src="{{ STATIC_URL }}js/lib/bootstrap/bootstrap.bundle.min.js"></script>
{% endblock %}

{% block meta %}
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
{% endblock %}

{% block header %}
    {% if user.is_superuser %}
      <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    {% else %}
      <nav class="navbar navbar-expand-md navbar-dark fixed-top" style="background-color: #0a588f;">
    {% endif %}
      <img alt="{{ VENUE.name }}" src="{{ STATIC_URL }}/{{ VENUE.internal_header_img }}" height="40px">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url "toolkit-index" %}">Home <span class="sr-only">(current)</span></a>
          </li>
          {% if user.is_superuser %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="{% url "default-edit" %}" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Diary</a>
              <div class="dropdown-menu" aria-labelledby="dropdown01">
                <a class="dropdown-item" href="{% url "default-edit" %}">Edit</a>
                <a class="dropdown-item" href="{% url "diary-edit-calendar" %}">Calendar</a>
              </div>
            </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="{% url "default-view" %}">Public Programme</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="{% url "rota-edit" %}" id="dropdown02" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Rota</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="dropdown-item" href="{% url "rota-edit" %}">Edit</a>
              <a class="dropdown-item" href="{% url "view-rota-vacancies" %}">Upcoming vacancies</a>
            </div>
          </li>
          {% if user.is_superuser %}
             <li class="nav-item dropdown">
               <a class="nav-link dropdown-toggle" href="{% url "search-members" %}" id="dropdown03" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Members</a>
               <div class="dropdown-menu" aria-labelledby="dropdown04">
                 <a class="dropdown-item" href="{% url "add-member" %}">Add Member</a>
                 <a class="dropdown-item" href="{% url "search-members" %}">Search Members</a>
                 <a class="dropdown-item" href="{% url "member-statistics" %}">Member Statistics</a>
                 <a class="dropdown-item" href="{% url "member-duplicates" %}">Member Duplicates</a>
               </div>
             </li>

             <li class="nav-item dropdown">
               <a class="nav-link dropdown-toggle" href="{% url "view-volunteer-summary" %}" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Volunteers</a>
               <div class="dropdown-menu" aria-labelledby="dropdown03">
                 <a class="dropdown-item" href="{% url "view-volunteer-summary" %}">Volunteers summary</a>
                 <a class="dropdown-item" href="{% url "view-volunteer-list" %}">Volunteers profiles</a>
                 <a class="dropdown-item" href="{% url "add-volunteer" %}">Add new volunteer</a>
                 <a class="dropdown-item" href="{% url "retire-select-volunteer" %}">Retire volunteer</a>
                 <a class="dropdown-item" href="{% url "unretire-select-volunteer" %}">Unretire volunteer</a>
                 <a class="dropdown-item" href="{% url "view-volunteer-export" %}">Export volunteers as CSV</a>
                 <a class="dropdown-item" href="{% url "view-volunteer-role-report" %}">Volunteer role report</a>
                 <a class="dropdown-item" href="{% url "view-volunteer-training-report" %}">Volunteer training report</a>
               </div>
             </li>
            </li>
          {% endif %}
          <li class="nav-item">
            <form id="base-admin-logout-form" method="post" action="{% url 'logout' %}">
              {% csrf_token %}
              <button class="nav-link" type="submit">Log out</button>
            </form>
          </li>
        </ul>
        {% block header-navbar-extra-post %}{% endblock %}
      </div>
    </nav>

    <div class="container">
        <div class="admin-template">
{% endblock %}

{% block body %}

{% endblock %}

{% block footer %}
        </div><!-- /.admin-template -->
    </div><!-- /.container -->
{% endblock %}

toolkit/index/templates/index_delete_form.html
{% extends "base_admin.html" %}

{% block title %}
{{ VENUE.longname }} Toolkit: Delete link
{% endblock %}

{% block body %}
<h1>Delete link: {% firstof object.text object.link %}</h1>
<h2>Are you sure?</h2>
{% if message %}<h3>{{ message }}</h3>{% endif %}
<form method="POST">
{% csrf_token %}
{{ form.as_p }}
<p><input type="submit" value="Delete"> <a href="{% url "toolkit-index" %}">Cancel</a></p>
</form>

{% endblock %}

toolkit/index/templates/index_generic_form.html
{% extends "base_admin.html" %}

{% block title %}
{{ VENUE.longname }} Toolkit: Create/edit item
{% endblock %}

{% block css %}
{{ block.super }}
<style>
input[type="text"] {
    width: 90%;
}
</style>
{% endblock %}

{% block body %}
<h1>Create/edit item</h1>
{% if message %}<h3>{{ message }}</h3>{% endif %}
<form method="POST">
{% csrf_token %}
{{ form.as_p }}
<p><input type="submit" value="Save"> <a href="{% url "toolkit-index" %}">Cancel</a></p>
</form>

{% endblock %}

toolkit/index/templates/toolkit_index.html
{% extends "base_admin.html" %}

{% block title %}
{{ VENUE.longname }} Toolkit
{% endblock %}

{% block css %}
{{ block.super }}
<style>
    .index-edit {
        color: #a3a3a3;
        font-size: 8pt;
    }
    .index-edit a {
        color: #a3a3a3;
    }
    #logout-form {
      display: inline;
    }
    #logout-form button {
      background: none;
      border: none;
      cursor: pointer;
      padding: 0;
      color: #007bff;
    }
    #logout-form button:hover {
        text-decoration: underline;
    }
</style>
{% endblock %}

{% block body %}
<h1>{{ VENUE.longname }} Toolkit</h1>

<h2>Programming</h2>
<ul>
    <li><a href="{% url "default-view" %}">Diary for the public</a></li>
    <li><a href="{% url "archive-view-index" %}">Public diary archive</a></li>
    {% if user.is_superuser %}
        <li><a href="{% url "default-edit" %}">Edit the diary</a></li>
        <li><a href="{% url "diary-edit-calendar" %}">Edit the diary from a calendar</a></li>
        <li><a href="{% url "view_event_field" field="copy" %}">Copy report</a></li>
        <li><a href="{% url "view_event_field" field="copy_summary" %}">Copy summary report</a></li>
        <li><a href="{% url "view_event_field" field="terms" %}">Terms report</a></li>
        <li><a href="{% url "edit-printed-programmes" %}">Upload printed programme PDFs</a></li>
    {% endif %}
</ul>
<h2>Rota</h2>
<ul>
    <li><a href="{% url "rota-edit" %}">Edit the rota</a></li>
    <li><a href="{% url "view-rota-vacancies" %}">List vacancies in the next 30 days</a> (for easy emailing)</li>
</ul>

{% if user.is_superuser %}

    <h2>Meta-programming</h2>
    <ul>
        <li><a href="{% url "edit_event_tags" %}">Edit available event tags</a></li>
        <li><a href="{% url "edit_event_templates" %}">Edit available event templates</a></li>
        <li><a href="{% url "edit_roles" %}">Edit available volunteer/event roles</a></li>
   </ul>

    <h2>Volunteers</h2>
    <ul>
        <li><a href="{% url "view-volunteer-summary" %}">Volunteers summary</a></li>
        <li><a href="{% url "view-volunteer-list" %}">Volunteers profiles</a></li>
        <li><a href="{% url "view-volunteer-role-report" %}">Volunteer role report</a></li>
        <li><a href="{% url "view-volunteer-export" %}">Export volunteers as CSV</a></li>
        <li><a href="{% url "add-volunteer-training-group-record" %}">Add volunteer training records</a></li>
        <li><a href="{% url "view-volunteer-training-report" %}">Volunteer training report</a></li>
    </ul>

    <h2>Members</h2>
    <ul>
        <li><a href="{% url "add-member" %}">Members database</a></li>
        <li><a href="{% url "member-homepages" %}">Members homepages</a></li>
        <li><a href="{% url "members-mailout" %}">Send a members mailout</a></li>
        <li><a href="{% url "mailer:jobs-list" %}">Mailout job status</a></li>
        <li><a href="{% url "member-statistics" %}">Members statistics</a></li>
        <li><a href="{% url "member-duplicates" %}">Members duplicates</a></li>
    </ul>
    <h2>Website</h2>
    <ul>
        <li><a href="{% url "wagtailadmin_home" %}">Content management</a></li>
    </ul>

{% endif %}

<ul>
{% for link in object_list %}
{% ifchanged link.category %}
</ul>
<h2>{{ link.category.name }}
    <span class="index-edit">[<a href="{% url "update-index-category" pk=link.category.pk %}">e</a>]</span></h2>
<ul>
{% endifchanged %}
<li><a href="{{ link.link }}">{% firstof link.text link.link %}</a> <span class="index-edit">
[<a href="{% url "update-index-link" pk=link.pk %}">e</a>]
[<a href="{% url "delete-index-link" pk=link.pk %}">x</a>]
</span></li>
{% endfor %}
</ul>
<hr>
<p>You logged in as {{ user }} at {{ user.last_login }}</p>
{% if user.is_superuser %}
    <a href="{% url "create-index-link" %}">Add link</a> &#xb7;
    <a href="{% url "create-index-category" %}">Add link group</a> &#xb7;
{% endif %}
{% if VENUE.show_user_management %}
    <a href="{% url "password_change" %}">Change password</a> &#xb7;
{% endif %}
<form id="logout-form" method="post" action="{% url 'logout' %}">
  {% csrf_token %}
  <button type="submit">Log out</button>
</form>
<p>

{% endblock %}